### ISSUE TITLE
opencv2

### ISSUE THREAD

**Issue by dradri** [luav/FIMTrack#2]
On Mac OS 10.14.6 
Got most of the way through without issues, but on the final make command:

(base) BIOLMAC51:FIMTrack leboeufa$ make
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -stdlib=libc++ -Wall -std=c++11 -Wall -pedantic -Wno-unknown-pragmas -O2 -std=gnu++11  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wno-unused-variable -Wno-reorder -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/include -I/usr/include/opencv4 -I/usr/include/opencv4 -I/opt/anaconda3/include/qt -I/opt/anaconda3/include/qt/QtPrintSupport -I/opt/anaconda3/include/qt/QtWidgets -I/opt/anaconda3/include/qt/QtGui -I/opt/anaconda3/include/qt/QtCore -Ibuild/release -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -Ibuild/release -I/opt/anaconda3/mkspecs/macx-clang -o build/release/Hungarian.o Algorithm/Hungarian.cpp
In file included from Algorithm/Hungarian.cpp:1:
In file included from Algorithm/Hungarian.hpp:37:
./Configuration/FIMTrack.hpp:39:10: fatal error: 'opencv2/opencv.hpp' file not
      found
#include <opencv2/opencv.hpp>

**Comment by luav** [comment]
Fixed by 90a6be4bf10f30b491ac7e97e3dc4b7736c1e5f8
